version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: attendance_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: attendance_db
      MYSQL_USER: attendance_user
      MYSQL_PASSWORD: attendance_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - attendance_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend API
  backend:
    build: ./backend
    container_name: attendance_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: mysql
      DB_USER: attendance_user
      DB_PASSWORD: attendance_pass
      DB_NAME: attendance_db
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - attendance_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend
  frontend:
    build: ./frontend
    container_name: attendance_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - attendance_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  mysql_data:

networks:
  attendance_network:
    driver: bridge
